m1s1: Add VR composer to manifest
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554] files are incompatible: Device manifest and framework compatibility matrix are incompatible: HALs incompatible. Matrix level = 2. Manifest level = 2. The following re
quirements are not met:
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554] android.hardware.graphics.composer:
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554]     required: @2.1::IComposer/vr
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554]     provided: @2.1::IComposer/default
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554] android.hardware.graphics.composer:
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554]     required: @2.3::IComposer/vr
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554]     provided: @2.1::IComposer/default
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554]
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554] The following instances are in the device manifest but not specified in framework compatibility matrix:
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554]     vendor.nxp.nxpnfc@1.0::INxpNfc/default
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554] Suggested fix:
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554] 1. Update deprecated HALs to the latest version.
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554] 2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 2.
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554] 3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 2 where applicable.
checkvintf E 02-25 13:41:36 35819 35819 check_vintf.cpp:554] 4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success

Traceback (most recent call last):
  File "/mnt/Data/out/lineage-18/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/mnt/Data/out/lineage-18/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 72, in _run_code
  File "/mnt/Data/out/lineage-18/host/linux-x86/bin/ota_from_target_files/__main__.py", line 12, in <module>
  File "/mnt/Data/out/lineage-18/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/mnt/Data/out/lineage-18/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 72, in _run_code
  File "/mnt/Data/out/lineage-18/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 2300, in <module>
  File "/mnt/Data/out/lineage-18/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 2273, in main
  File "/mnt/Data/out/lineage-18/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 1957, in GenerateAbOtaPackage
  File "/mnt/Data/out/lineage-18/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 630, in CheckVintfIfTrebleEnabled
RuntimeError: VINTF compatibility check failed
13:41:37 ninja failed with: exit status 1

Signed-off-by: electimon <electimon@gmail.com>
Change-Id: I5ac0ab29e5f2fc6265adf6311b93ef0942999cde